display_errors=On
error_reporting=E_ALL
upload_max_filesize=20M
post_max_size=20M
memory_limit=256M
opcache.enable=1
opcache.memory_consumption=64
opcache.max_accelerated_files=1000
opcache.revalidate_freq=60